---
git:
  tagName: "v${version}"
  commitMessage: 'chore(release): v${version}'
  changelog: npx auto-changelog --breaking-pattern "BREAKING CHANGE:" --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs

github:
  release: true

npm: false

hooks:
  after:bump: ["npx auto-changelog --breaking-pattern 'BREAKING CHANGE:' --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs", "node ./~Scripts/update_package_version.js ${version}"]
