# Workflow for updating the upm branch automatically.

name: upm

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  UICOMPONENTS_PATH: 'Assets/UIComponents'
  BRANCH_NAME: upm

jobs:
  run:
    name: Update UPM branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy meta files to package folder
        run: cp CHANGELOG.md CHANGELOG.md.meta LICENSE LICENSE.meta README.md README.md.meta "$UICOMPONENTS_PATH"
      - name: Create commit for the meta files
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git add -A
          git commit -am "chore(ci): prepare upm branch"
      - name: Split subtree
        run: git subtree split -P "$UICOMPONENTS_PATH" -b "$BRANCH_NAME"
      - name: Push subtree
        run: git push origin "$BRANCH_NAME"
